<a href="https://colab.research.google.com/github/enoamoo/eno/blob/master/Amoo_Eno_stage_C_quiz_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing libraries

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#uploading data
csv_df=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00471/Data_for_UCI_named.csv')
df = csv_df
df.describe(include='all')

tau1          tau2  ...          stab     stabf
count   10000.000000  10000.000000  ...  10000.000000     10000
unique           NaN           NaN  ...           NaN         2
top              NaN           NaN  ...           NaN  unstable
freq             NaN           NaN  ...           NaN      6380
mean        5.250000      5.250001  ...      0.015731       NaN
std         2.742548      2.742549  ...      0.036919       NaN
min         0.500793      0.500141  ...     -0.080760       NaN
25%         2.874892      2.875140  ...     -0.015557       NaN
50%         5.250004      5.249981  ...      0.017142       NaN
75%         7.624690      7.624893  ...      0.044878       NaN
max         9.999469      9.999837  ...      0.109403       NaN

[11 rows x 14 columns]

In [ ]:
#check distribution of target variable
df['stabf'].value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [ ]:
#dropping 'stab' column
df.drop(columns = 'stab', inplace=True)

In [ ]:
#split the data into training and testing sets
X = df.drop(columns='stabf')
y = df['stabf']
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=1)
y_train.value_counts()

unstable    5092
stable      2908
Name: stabf, dtype: int64

# Feature Scaling

In [ ]:
#feature scaling 
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# RandomForest CLassifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
from sklearn.metrics import classification_report, recall_score, accuracy_score, precision_score, f1_score, confusion_matrix
predictions = clf.predict(x_test)
#printing Accuracy
accuracy = accuracy_score(y_test, predictions)
print('Accuracy: {}'.format(round(accuracy*100), 2))

Accuracy: 92.0


In [ ]:
#prints confusion_matrix
print(confusion_matrix(y_test, predictions))

[[ 625   87]
 [  64 1224]]


In [ ]:
#prints Precision
precision = precision_score(y_test, predictions,pos_label='stable')
print('Precision: {}'.format(round(precision*100), 2))

Precision: 91.0


In [ ]:
#prints Recall
recall = recall_score(y_test, predictions, pos_label='stable')
print('Recall: {}'.format(round(recall*100), 2))

Recall: 88.0


In [ ]:
#prints F1_Score
f1 = f1_score(y_test, predictions, pos_label='stable')
print('F1: {}'.format(round(f1*100), 2))

F1: 89.0


# ExtraTree Classifier

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier
xtree = ExtraTreesClassifier()
n_estimators = [50, 100, 300, 500, 1000]

min_samples_split = [2, 3, 5, 7, 9]

min_samples_leaf = [1, 2, 4, 6, 8]

max_features = ['auto', 'sqrt', 'log2', None] 

In [ ]:
hyperparameter_grid = {'n_estimators': n_estimators,

                       'min_samples_leaf': min_samples_leaf,

                       'min_samples_split': min_samples_split,

                       'max_features': max_features}

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
clf = RandomizedSearchCV(xtree, hyperparameter_grid, random_state=1)
clf.fit(x_train, y_train)

RandomizedSearchCV(cv=None, error_score=nan,
                   estimator=ExtraTreesClassifier(bootstrap=False,
                                                  ccp_alpha=0.0,
                                                  class_weight=None,
                                                  criterion='gini',
                                                  max_depth=None,
                                                  max_features='auto',
                                                  max_leaf_nodes=None,
                                                  max_samples=None,
                                                  min_impurity_decrease=0.0,
                                                  min_impurity_split=None,
                                                  min_samples_leaf=1,
                                                  min_samples_split=2,
                                                  min_weight_fraction_leaf=0.0,
                                     

In [ ]:
xtree_pred = clf.predict(x_test)

In [ ]:
print(classification_report(y_test, xtree_pred))

              precision    recall  f1-score   support

      stable       0.92      0.87      0.90       712
    unstable       0.93      0.96      0.94      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000



In [ ]:
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix
# Prints Accuracy
predictions = clf.predict(x_test)
accuracy = accuracy_score(y_test, xtree_pred)
print('Accuracy: {}'.format(round(accuracy*100), 2))

Accuracy: 93.0


In [ ]:
#Confusion_Matrix
cnf_mat = confusion_matrix(y_test, xtree_pred)
print(cnf_mat)

[[ 620   92]
 [  53 1235]]


# XGBOOST and LIGHTGBM

In [ ]:
pip install xgboost

In [ ]:
!pip install lightgbm

In [ ]:
from lightgbm import LGBMClassifier

In [ ]:
lgbm = LGBMClassifier(random_state=1)

In [ ]:
lgbm.fit(x_train, y_train)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=1, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [ ]:
from xgboost import XGBClassifier

In [ ]:
xgb = XGBClassifier(random_state=1)
xgb.fit(x_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=1,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [ ]:
xgb_pred = xgb.predict(x_test)

In [ ]:
lgbm_pred = lgbm.predict(x_test)

In [ ]:
print('classification Report of XGBoost\n', classification_report(y_test, xgb_pred))

classification Report of XGBoost
               precision    recall  f1-score   support

      stable       0.92      0.85      0.88       712
    unstable       0.92      0.96      0.94      1288

    accuracy                           0.92      2000
   macro avg       0.92      0.90      0.91      2000
weighted avg       0.92      0.92      0.92      2000



In [ ]:
print(confusion_matrix(y_test,xgb_pred))

[[ 603  109]
 [  52 1236]]


In [ ]:
print(accuracy_score(y_test,xgb_pred).round(2))

0.92


In [ ]:
print('classification Report of Lightgbm\n', classification_report(y_test, lgbm_pred))

classification Report of Lightgbm
               precision    recall  f1-score   support

      stable       0.93      0.89      0.91       712
    unstable       0.94      0.96      0.95      1288

    accuracy                           0.94      2000
   macro avg       0.94      0.93      0.93      2000
weighted avg       0.94      0.94      0.94      2000



In [ ]:
print(confusion_matrix(y_test,lgbm_pred))

[[ 635   77]
 [  48 1240]]


In [ ]:
print(accuracy_score(y_test,lgbm_pred).round(2))

0.94
